### ISSUE TITLE
How is the SwinTransformer backbone initialized?

### ISSUE THREAD

**Issue by hellojialee** [zyh-uaiaaaa/Mine-Extra-Knowledge#1]
Thank you for your sharing. 
Could you please tell me How SwinTransformer backbone is initialized? Is it pre-trained on ImageNet-1k or something else, if we want to train the model of this repo?

**Comment by zyh-uaiaaaa** [comment]
Hi, it is pre-trained on MS-Celeb-1M. You can download all you need from the [link](https://drive.google.com/file/d/1GiVsA5sbhc-12brGrKdTIdrKZnXz9vtZ/view?usp=drive_link).

**Comment by hellojialee** [comment]
Thank you for your reply. It is pre-trained in a fully-supervised manner on MS-Celeb-1M, i.e. using the labels of this large dataset?

**Comment by zyh-uaiaaaa** [comment]
Yes, as the backbone is utilized to extract face features, which is further used for FER.

**Comment by hellojialee** [comment]
Thank you for your rely :) Thumbs Up
